services:
  - type: web
    name: chess-analysis-api
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port 8000
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: DB_URL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
